[package]
name = "rust-graphing-calc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lalrpop-util = "0.19.1"
regex = "1"
"colored" = "2.0.0"
arithmetic-parser = "0.3.0"